# -*- coding: utf-8 -*-
"""Święty Mikołaj

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JoXa73H27QnTKwCAC3bollsdlscm1g4V
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

# Konfiguracja strony Streamlit
st.set_page_config(layout="centered", page_title="Interaktywny Mikołaj Matplotlib")
st.title("🎅 Interaktywny Święty Mikołaj i Choinka")
st.markdown("Użyj suwaka poniżej, aby zmienić kolor płaszcza Mikołaja.")

# --- Funkcja do rysowania Mikołaja (nie zmieniona) ---
def draw_santa(ax, center_x, center_y, scale=1.0, color='red'):
    """Rysuje Mikołaja."""

    # Głowa (okrąg)
    head_radius = 0.3 * scale
    head = patches.Circle((center_x, center_y + 1.2 * scale), head_radius, facecolor='peachpuff', edgecolor='black', lw=0.5)
    ax.add_patch(head)

    # Oczy
    ax.plot(center_x - 0.1 * scale, center_y + 1.25 * scale, 'o', markersize=3 * scale, color='black')
    ax.plot(center_x + 0.1 * scale, center_y + 1.25 * scale, 'o', markersize=3 * scale, color='black')

    # Broda
    beard_x = [center_x - 0.3 * scale, center_x - 0.5 * scale, center_x, center_x + 0.5 * scale, center_x + 0.3 * scale]
    beard_y = [center_y + 0.9 * scale, center_y + 0.4 * scale, center_y + 0.6 * scale, center_y + 0.4 * scale, center_y + 0.9 * scale]
    beard = patches.Polygon(list(zip(beard_x, beard_y)), closed=True, facecolor='white', edgecolor='black', lw=0.5)
    ax.add_patch(beard)

    # Tułów (prostokąt)
    body_width = 1.0 * scale
    body_height = 1.5 * scale
    body = patches.Rectangle((center_x - body_width/2, center_y - body_height/2), body_width, body_height, facecolor=color, edgecolor='black', lw=0.5)
    ax.add_patch(body)

    # Pas
    belt_y = center_y + 0.1 * scale
    belt = patches.Rectangle((center_x - body_width/2, belt_y - 0.1 * scale/2), body_width, 0.1 * scale, facecolor='black', edgecolor='black', lw=0.5)
    ax.add_patch(belt)
    # Klamra pasa
    buckle = patches.Rectangle((center_x - 0.15 * scale, belt_y - 0.15 * scale), 0.3 * scale, 0.3 * scale, facecolor='gold', edgecolor='black', lw=0.5)
    ax.add_patch(buckle)

    # Czapka
    hat_x = [center_x - 0.3 * scale, center_x + 0.3 * scale, center_x + 0.1 * scale, center_x - 0.0 * scale]
    hat_y = [center_y + 1.4 * scale, center_y + 1.4 * scale, center_y + 2.0 * scale, center_y + 1.4 * scale]
    hat = patches.Polygon(list(zip(hat_x, hat_y)), closed=True, facecolor=color, edgecolor='black', lw=0.5)
    ax.add_patch(hat)
    # Biały pompon
    pompon = patches.Circle((center_x + 0.1 * scale, center_y + 2.0 * scale), 0.1 * scale, facecolor='white', edgecolor='black', lw=0.5)
    ax.add_patch(pompon)
    # Białe futerko na czapce
    hat_fur = patches.Rectangle((center_x - 0.3 * scale, center_y + 1.35 * scale), 0.6 * scale, 0.1 * scale, facecolor='white', edgecolor='black', lw=0.5)
    ax.add_patch(hat_fur)

    # Ręce
    arm_radius = 0.15 * scale
    left_arm = patches.Circle((center_x - 0.6 * scale, center_y + 0.5 * scale), arm_radius, facecolor=color, edgecolor='black', lw=0.5)
    right_arm = patches.Circle((center_x + 0.6 * scale, center_y + 0.5 * scale), arm_radius, facecolor=color, edgecolor='black', lw=0.5)
    ax.add_patch(left_arm)
    ax.add_patch(right_arm)

    # Nogawki (ukryte pod spodem, dla efektu)
    ax.plot([center_x - 0.3 * scale, center_x + 0.3 * scale], [center_y - 0.75 * scale, center_y - 0.75 * scale], color='black', linewidth=10 * scale, solid_capstyle='butt')

# --- Funkcja do rysowania Worka Prezentów (nie zmieniona) ---
def draw_bag(ax, center_x, center_y, scale=1.0):
    """Rysuje worek prezentów."""
    bag_width = 1.0 * scale
    bag_height = 1.2 * scale

    # Worek (kształt nieregularny)
    bag_x = [center_x - bag_width/2, center_x - bag_width/2 - 0.1, center_x + bag_width/2 + 0.1, center_x + bag_width/2]
    bag_y = [center_y, center_y - bag_height, center_y - bag_height, center_y]
    bag = patches.Polygon(list(zip(bag_x, bag_y)), closed=True, facecolor='brown', edgecolor='black', lw=1.0)
    ax.add_patch(bag)

    # Zaciśnięcie worka
    tie = patches.Rectangle((center_x - bag_width/2, center_y - 0.1), bag_width, 0.1, facecolor='darkred', edgecolor='black', lw=1.0)
    ax.add_patch(tie)

    # Wystające prezenty (przykłady)
    present1 = patches.Rectangle((center_x - 0.4, center_y + 0.1), 0.3, 0.3, facecolor='yellow', edgecolor='black')
    present2 = patches.Rectangle((center_x + 0.1, center_y + 0.2), 0.4, 0.2, facecolor='green', edgecolor='black')
    ax.add_patch(present1)
    ax.add_patch(present2)

# --- Funkcja do rysowania Choinki (nie zmieniona) ---
def draw_christmas_tree(ax, center_x, center_y, scale=1.0):
    """Rysuje choinkę z bombkami i światełkami."""

    # Pień
    trunk = patches.Rectangle((center_x - 0.1 * scale, center_y - 0.5 * scale), 0.2 * scale, 0.5 * scale, facecolor='saddlebrown', edgecolor='black')
    ax.add_patch(trunk)

    # Korona choinki (trzy trójkąty)
    x = np.array([center_x - 1.5 * scale, center_x + 1.5 * scale, center_x])
    y = np.array([center_y - 0.5 * scale, center_y - 0.5 * scale, center_y + 0.5 * scale])

    # Dolna część
    tree_base = patches.Polygon(list(zip(x, y)), closed=True, facecolor='green', edgecolor='darkgreen', lw=1.0)
    ax.add_patch(tree_base)

    # Środkowa część
    tree_mid = patches.Polygon(list(zip(x * 0.8 + center_x * 0.2, y * 0.8 + center_y * 0.2 + 0.5 * scale)),
                               closed=True, facecolor='green', edgecolor='darkgreen', lw=1.0)
    ax.add_patch(tree_mid)

    # Górna część
    tree_top = patches.Polygon(list(zip(x * 0.6 + center_x * 0.4, y * 0.6 + center_y * 0.4 + 1.0 * scale)),
                               closed=True, facecolor='green', edgecolor='darkgreen', lw=1.0)
    ax.add_patch(tree_top)

    # Gwiazda na szczycie
    ax.plot(center_x, center_y + 1.7 * scale, '*', markersize=15, color='gold', markeredgecolor='darkgoldenrod')

    # Ozdoby (bombki i światełka)

    # Światełka (małe, kolorowe kropki)
    lights_coords = [
        (center_x - 1.0, center_y - 0.1), (center_x + 0.8, center_y - 0.3),
        (center_x - 0.5, center_y + 0.4), (center_x + 0.2, center_y + 0.8),
        (center_x - 0.3, center_y + 1.2), (center_x + 0.5, center_y + 0.1)
    ]
    lights_colors = ['red', 'blue', 'yellow', 'cyan', 'magenta', 'lime']
    for (lx, ly), lc in zip(lights_coords, lights_colors):
        ax.plot(lx * scale, ly * scale, 'o', markersize=5 * scale, color=lc)

    # Bombki (większe kropki)
    ornaments_coords = [
        (center_x - 1.2, center_y - 0.4), (center_x + 1.1, center_y - 0.4),
        (center_x - 0.7, center_y + 0.1), (center_x + 0.7, center_y + 0.3),
        (center_x, center_y + 1.0)
    ]
    ornaments_colors = ['darkred', 'darkblue', 'orange', 'purple', 'silver']
    for (ox, oy), oc in zip(ornaments_coords, ornaments_colors):
        ax.plot(ox * scale, oy * scale, 'o', markersize=10 * scale, color=oc, markeredgecolor='black')

    # Łańcuchy (linie lub punkty wzdłuż "gałęzi")
    chain_x = np.linspace(center_x - 1.5, center_x + 1.5, 30) * scale
    chain_y = -0.05 * (chain_x - center_x * scale)**2 + center_y * scale + 0.1 * scale
    ax.plot(chain_x, chain_y, ':', color='silver', linewidth=2)


# --- Funkcja do mapowania wartości suwaka na kolor ---
COLOR_MAP = {
    "Czerwony (klasyczny)": 'red',
    "Niebieski (zimowy)": 'blue',
    "Zielony (leśny)": 'green',
    "Purpurowy (królewski)": 'purple'
}

def get_color_from_value(color_name):
    """Zwraca kod koloru na podstawie nazwy wybranej w Streamlit."""
    return COLOR_MAP.get(color_name, 'red')

# --- Główna funkcja rysująca wykres ---
def create_plot(selected_color_name):
    """Tworzy figurę Matplotlib i rysuje scenę."""

    # Inicjalizacja figury i osi wewnątrz funkcji (ważne dla Streamlit)
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 8)
    ax.set_aspect('equal', adjustable='box')
    ax.axis('off')

    # Pobranie kodu koloru
    color = get_color_from_value(selected_color_name)

    # Pozycjonowanie elementów
    santa_x, santa_y = 3.0, 3.5
    bag_x, bag_y = 4.5, 3.0
    tree_x, tree_y = 8.0, 3.5

    # Rysowanie
    draw_santa(ax, santa_x, santa_y, scale=1.0, color=color)
    draw_bag(ax, bag_x, bag_y, scale=1.0)
    draw_christmas_tree(ax, tree_x, tree_y, scale=1.0)

    # Tło/Napisy
    ax.text(5, 7.5, "Wesołych Świąt!", fontsize=20, ha='center', color='darkred')
    ax.text(3.0, 0.5, "Święty Mikołaj", fontsize=12, ha='center')
    ax.text(8.0, 0.5, "Choinka", fontsize=12, ha='center')

    return fig

# --- Interfejs użytkownika Streamlit (zamiennik dla suwaka Matplotlib) ---

# Streamlit używa widżetów (np. selectbox, slider), które automatycznie przeładowują aplikację
# i przekazują wartość do funkcji.

selected_color_name = st.selectbox(
    "Wybierz kolor płaszcza Mikołaja:",
    options=list(COLOR_MAP.keys()),
    index=0,
    help="Zmiana koloru spowoduje automatyczne odświeżenie rysunku."
)

# Rysowanie i wyświetlanie wykresu
santa_plot = create_plot(selected_color_name)
st.pyplot(santa_plot)

st.caption("Aplikacja stworzona za pomocą bibliotek Matplotlib i Streamlit.")